tasks:
  - init: nvm install 16.15 && nvm use 16.15 && npm adduser && yarn install && yarn preview
    command: nvm install 16.15 && nvm use 16.15 && yarn install && yarn preview
vscode:
  extensions:
    - GraphQL.vscode-graphql
    - kumar-harsh.graphql-for-vscode
    - dsznajder.es7-react-js-snippets
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint