const QUERY_RUNNING = 'RUNNING'
const QUERY_CANCELING = 'CANCELING'
const QUERY_COMPLETED = 'COMPLETED'
const QUERY_EXPIRED = 'EXPIRED'
const QUERY_CREATED = 'CREATED'

module.exports = {
  QUERY_RUNNING,
  QUERY_CANCELING,
  QUERY_COMPLETED,
  QUERY_EXPIRED,
  QUERY_CREATED,
}
